on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '23 14 * * 2'

name: build
jobs:
  generate-matrix:
    name: "Generate matrix from cabal"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@v0.1.6.0
        with:
          cabal-file: monad-schedule.cabal
          ubuntu: true
          version: 0.1.6.0

  build:
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    name: Haskell GHC ${{ matrix.ghc }} cabal
    steps:
      - uses: actions/checkout@v4
      - uses: haskell/actions/setup@v2
        id: setup-haskell-build
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Cache Cabal build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell-build.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ matrix.ghc }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ matrix.ghc }}
      - name: Cabal build dependencies
        run: |
          cabal build all  --enable-tests --only-dependencies
      - name: Cabal build packages
        run: |
          cabal build all --enable-tests
      - name: Cabal test
        run: |
          cabal test all --enable-tests --test-show-details=Always
